name: make_memories
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  esc_pos_utils_plus: ^2.0.4
  blue_thermal_printer: ^1.1.5
  image: ^4.0.17

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
